# Generated by Django 4.2.1 on 2023-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tagat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("object", models.TextField(blank=True, null=True)),
                ("idobject", models.TextField(blank=True, null=True)),
                ("shortname", models.TextField(blank=True, null=True)),
                ("inn", models.TextField(blank=True, null=True)),
                (
                    "tarif",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("idsystem", models.BigIntegerField(blank=True, null=True)),
                ("kpp", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("dbeg", models.DateTimeField(blank=True, null=True)),
                ("dend", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tagat",
                "db_table_comment": "Дополнительная разбивка одной учетной записи по ИНН. Впервые возникла необходимость для агат-проекта",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tdata",
            fields=[
                ("login", models.TextField(blank=True, null=True)),
                ("idlogin", models.TextField(blank=True, null=True)),
                ("idsystem", models.IntegerField(blank=True, null=True)),
                ("object", models.TextField(blank=True, null=True)),
                ("idobject", models.TextField(blank=True, null=True)),
                ("isactive", models.TextField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dimport", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tdata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Temail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("inn", models.TextField(blank=True, null=True)),
                ("kpp", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "temail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tklient",
            fields=[
                ("name", models.TextField(blank=True, null=True)),
                ("shortname", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("inn", models.TextField(blank=True, null=True)),
                ("kpp", models.TextField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tarif",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tklient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ttarif",
            fields=[
                (
                    "tarif",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("dbeg", models.DateTimeField(blank=True, null=True)),
                ("dend", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "ttarif",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Twialon100",
            fields=[
                ("klient", models.TextField(blank=True, null=True)),
                ("login", models.TextField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("logintd", models.TextField(blank=True, null=True)),
                ("tkid", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "twialon100",
                "db_table_comment": "Таблица учетных записей Клиента. Исторически сформированная на основания Google таблицы Wialon100. Является вспомогательной таблицей для соединения объекта мониторинга и клиента.",
                "managed": False,
            },
        ),
    ]
